name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build and Deploy
      uses: ApolloZhu/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACESS_TOKEN }}
        PUBLISH_REPOSITORY: wulnm/wulnm.github.io # The repository the action should deploy to.
        BRANCH: main # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.